blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:pk>/", views.blog_detail, name="blog_detail"),
    path("<category>/", views.blog_category, name="blog_category"),
]

cargo_storage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("projects/", include("projects.urls")),
    path("blog/", include("blog.urls")),
    path("", include("main.urls")),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("index/", views.index, name="index"),
    path("docs/", views.docs, name="docs"),
    path("reports/", views.get_items_report, name="reports"),

    path("docs/in/", views.docs_in, name="docs_in"),
    path("docs/in/create/", views.docs_in_create, name="docs_in_create"),
    path("docs/in/<int:item_id>/del_item", views.docs_in_del_item, name="docs_in_del_item"),
    path("docs/in/<int:document_id>/add_item", views.docs_in_add_item, name="docs_in_add_item"),
    path("docs/in/<int:document_id>/", views.docs_in_edit, name="docs_in_edit"),
    path("docs/in/print/<int:document_id>/", views.docs_in_print, name="docs_in_print"),

    path("docs/out/", views.docs_out, name="docs_out"),
    path("docs/out/create/", views.docs_out_create, name="docs_out_create"),
    path("docs/out/<int:item_id>/del_item", views.docs_out_del_item, name="docs_out_del_item"),
    path("docs/out/<int:document_id>/add_item", views.docs_out_add_item, name="docs_out_add_item"),
    path("docs/out/<int:document_id>/", views.docs_out_edit, name="docs_out_edit"),
    path("docs/out/print/<int:document_id>/", views.docs_out_print, name="docs_out_print"),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.utils import timezone


class Operation(models.Model):
    operation_type = models.IntegerField('Тип операции', default=0)
    status = models.IntegerField('Статус', default=0)
    date_created = models.DateTimeField('date created', default=datetime.now)
    description = models.CharField(max_length=200)
    user_created = models.ForeignKey(User, null=True, blank=True, related_name='operations',
                                     verbose_name='Пользователь создавший операцию',
                                     on_delete=models.SET_NULL)

    def __str__(self):
        return "Operation: {}, created: {}, description: {}".format(self.pk, self.date_created, self.description)


class Document(models.Model):
    doc_type = models.IntegerField('Тип документа', default=0)
    date_created = models.DateTimeField('date created', default=datetime.now)
    doc_number = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    operation = models.ForeignKey(Operation, null=True, blank=True, on_delete=models.SET_NULL,
                                  related_name='documents')

    def __str__(self):
        return "Document: {}, created: {}, description: {}".format(self.pk, self.date_created, self.description)


class Item(models.Model):
    date_created = models.DateTimeField('date created', default=datetime.now)
    description = models.CharField(max_length=200, default="")
    name = models.CharField(max_length=60)
    weight = models.IntegerField('Вес', default=0)
    factory_number = models.CharField(max_length=60, default="")
    passport_number = models.CharField(max_length=60, default="")

    def __str__(self):
        return "Item {}, created: {}, description: {}".format(self.pk, self.date_created, self.description)


class ItemEntry(models.Model):
    date_created = models.DateTimeField('date created', default=datetime.now)
    description = models.CharField(max_length=200)
    operation = models.ForeignKey(Operation, null=True, blank=True, on_delete=models.SET_NULL,
                                  related_name='entries')
    item = models.ForeignKey(Item, null=True, blank=True, on_delete=models.SET_NULL,
                             related_name='entries')

    def __str__(self):
        return "ItemEntry {}, created: {}, description: {}".format(self.pk, self.date_created, self.description)


class UserProfile(User):
    date_created = models.DateTimeField('date created', default=datetime.now)
    full_name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return "UserProfile {}, created: {}, full_name: {}".format(self.pk, self.date_created, self.full_name)

main/forms.py
from django import forms


class DocumentForm(forms.Form):
    doc_number = forms.CharField(
        label="Номер документа",
        max_length=60,
        widget=forms.TextInput(attrs={
            "placeholder": "Document number"
        })
    )
    description = forms.CharField(
        label="Описание",
        max_length=200,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Leave a description!"
            })
    )


class ItemForm(forms.Form):
    name = forms.CharField(
        label="Название груза",
        max_length=60,
        widget=forms.TextInput(attrs={
            "placeholder": "Введите название груза"
        })
    )
    factory_number = forms.CharField(
        label="Заводской номер",
        max_length=60,
        widget=forms.TextInput(attrs={
            "placeholder": "Введите заводской номер"
        })
    )
    passport_number = forms.CharField(
        label="Номер паспорта",
        max_length=60,
        widget=forms.TextInput(attrs={
            "placeholder": "Введите номер паспорта"
        })
    )
    weight = forms.IntegerField(
        label="Вес",
        widget=forms.NumberInput(attrs={
            "placeholder": "0"
        })
    )
    description = forms.CharField(
        label="Описание",
        max_length=200,
        widget=forms.Textarea(
            attrs={
                "placeholder": "Введите описание"
            })
    )

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout

# Create your views here.
from django.urls import reverse

from main.forms import DocumentForm, ItemForm
from main.models import Operation, Document, ItemEntry, Item


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
        else:
            return render(request, "login.html", {'invalid_login': "Введены неверные логин или пароль!"})
    return render(request, "login.html", {})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:login_view'))


@login_required
def index(request):
    return render(request, "index.html", {})


@login_required
def docs(request):
    """Хендлер кнопки Документы"""
    return render(request, "docs.html", {})


@login_required
def docs_in(request):
    """Хендлер кнопки Документы-Приходная накладная"""
    documents = Document.objects.filter(
        doc_number__isnull=False,
        doc_type=0
    ).exclude(doc_number='').values('pk', 'doc_number', 'date_created', 'description')
    doc_number = request.GET.get('doc_number')
    if doc_number:
        documents = documents.filter(doc_number=doc_number)
    context = {
        "documents": documents,
    }
    return render(request, "docs_in.html", context)


@login_required
def docs_in_create(request):
    operation = Operation(operation_type=0)
    operation.save()
    document = Document(doc_type=0, operation=operation)
    document.save()

    return HttpResponseRedirect(reverse('main:docs_in_edit', args=(document.pk,)))


@login_required
def docs_in_edit(request, document_id):
    """Хендлер кнопки Документы-Приходная накладная - Добавить/Изменить"""
    document = get_object_or_404(Document, pk=document_id, doc_type=0)

    if request.method == "POST":
        form = DocumentForm(request.POST)
        if form.is_valid():
            document.doc_number = form.cleaned_data["doc_number"]
            document.description = form.cleaned_data["description"]
            document.save()
            return HttpResponseRedirect(reverse('main:docs_in_edit', args=(document.pk,)))
    else:
        form = DocumentForm({"doc_number": document.doc_number, "description": document.description})

    result = []
    for e in document.operation.entries.all():
        result.append({
            'pk': e.pk,
            'name': e.item.name,
            'factory_number': e.item.factory_number,
            'passport_number': e.item.passport_number,
            'weight': e.item.weight,
        })
    context = {
        "items": result,
        "document": document,
        "form_doc": form,
        "form_item": ItemForm()
    }

    return render(request, "docs_in_edit.html", context)


@login_required
def docs_in_add_item(request, document_id):
    document = get_object_or_404(Document, pk=document_id, doc_type=0)

    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            # найдем такой же груз
            items = Item.objects.filter(factory_number=form.cleaned_data["factory_number"])
            if items.exists():
                # пока берем первый, но вообще единица должна быть уникальной
                item = items.first()
            else:
                item = Item(
                    name=form.cleaned_data["name"],
                    factory_number=form.cleaned_data["factory_number"],
                    passport_number=form.cleaned_data["passport_number"],
                    weight=form.cleaned_data["weight"],
                )
                item.save()
            entry = ItemEntry(
                description=form.cleaned_data["description"],
                item=item,
                operation=document.operation
            )
            entry.save()
    return HttpResponseRedirect(reverse('main:docs_in_edit', args=(document.pk,)))


@login_required
def docs_in_del_item(request, item_id):
    entry = get_object_or_404(ItemEntry, pk=item_id, operation__operation_type=0)
    document = entry.operation.documents.first()
    entry.delete()
    return HttpResponseRedirect(reverse('main:docs_in_edit', args=(document.pk,)))


@login_required
def docs_in_print(request, document_id):
    document = get_object_or_404(Document, pk=document_id, doc_type=0)

    result = []
    for e in document.operation.entries.all():
        result.append({'name': e.item.name})
    context = {
        "doc_number": document.doc_number,
        "date_created": document.date_created,
        "items": result,
    }
    return render(request, "docs_in_print.html", context)


@login_required
def docs_out(request):
    """Хендлер кнопки Документы-Расходная накладная"""
    documents = Document.objects.filter(
        doc_number__isnull=False,
        doc_type=1
    ).exclude(doc_number='').values('pk', 'doc_number', 'date_created', 'description')
    doc_number = request.GET.get('doc_number')
    if doc_number:
        documents = documents.filter(doc_number=doc_number)
    context = {
        "documents": documents,
    }
    return render(request, "docs_out.html", context)


@login_required
def docs_out_create(request):
    operation = Operation(operation_type=1)
    operation.save()
    document = Document(doc_type=1, operation=operation)
    document.save()

    return HttpResponseRedirect(reverse('main:docs_out_edit', args=(document.pk,)))


@login_required
def docs_out_edit(request, document_id, **kwargs):
    """Хендлер кнопки Документы-Расходная накладная - Добавить/Изменить"""
    document = get_object_or_404(Document, pk=document_id, doc_type=1)

    if request.method == "POST":
        form = DocumentForm(request.POST)
        if form.is_valid():
            document.doc_number = form.cleaned_data["doc_number"]
            document.description = form.cleaned_data["description"]
            document.save()
            return HttpResponseRedirect(reverse('main:docs_out_edit', args=(document.pk,)))
    else:
        form = DocumentForm({"doc_number": document.doc_number, "description": document.description})

    result = []
    for e in document.operation.entries.all():
        result.append({
            'pk': e.pk,
            'name': e.item.name,
            'factory_number': e.item.factory_number,
            'passport_number': e.item.passport_number,
            'weight': e.item.weight,
        })
    context = {
        "items": result,
        "document": document,
        "form_doc": form,
        "error_message": kwargs.get('error_message'),
    }

    return render(request, "docs_out_edit.html", context)


@login_required
def docs_out_print(request, document_id):
    document = get_object_or_404(Document, pk=document_id, doc_type=1)

    result = []
    for e in document.operation.entries.all():
        result.append({'name': e.item.name})
    context = {
        "doc_number": document.doc_number,
        "date_created": document.date_created,
        "items": result,
    }
    return render(request, "docs_out_print.html", context)


@login_required
def docs_out_add_item(request, document_id):
    document = get_object_or_404(Document, pk=document_id, doc_type=1)

    if request.method == "POST":
        # найдем такой же груз
        item = Item.objects.filter(factory_number=request.POST["factory_number"])
        if item.exists():
            item = item.first()
            # проверяем, что последней проводкой был приход
            entries = item.entries.values('pk', 'date_created', 'operation__operation_type').order_by('date_created')
            if entries.exists() and entries.last()['operation__operation_type'] == 0:
                entry = ItemEntry(item=item, operation=document.operation)
                entry.save()

    return HttpResponseRedirect(reverse('main:docs_out_edit', args=(document.pk, )))


@login_required
def docs_out_del_item(request, item_id):
    entry = get_object_or_404(ItemEntry, pk=item_id, operation__operation_type=1)
    document = entry.operation.documents.first()
    entry.delete()
    return HttpResponseRedirect(reverse('main:docs_out_edit', args=(document.pk,)))


@login_required
def get_items_report(request):
    item_name = request.GET.get('item_name')
    factory_number = request.GET.get('factory_number')
    status = request.GET.get('status')

    queryset = Item.objects.all()
    if item_name:
        queryset = queryset.filter(name__contains=item_name)
    if factory_number:
        queryset = queryset.filter(factory_number=factory_number)

    result = []
    for item in queryset:
        data = {
            'name': item.name,
            'factory_number': item.factory_number,
            'passport_number': item.passport_number,
            'weight': item.weight
        }
        # находим статус груза
        if item.entries.exists():
            last_entry = item.entries.last()
            if last_entry.operation.operation_type == 0:
                data['current_status'] = "На хранении"
                data['date_arrival'] = last_entry.date_created
                data['date_departure'] = ""
                data['entry_in'] = last_entry.operation.documents.last().doc_number
                data['entry_out'] = ""
            else:
                data['current_status'] = "Отгружен"
                last_arrival = item.entries.filter(operation__operation_type=0).order_by('date_created').last()
                data['date_arrival'] = last_arrival.date_created if last_arrival else item.date_created
                data['date_departure'] = last_entry.date_created

main/templates/docs.html
<h1>Документы</h1>
<h2><a href="{% url 'main:docs_in' %}">Приходные накладные</a></h2>
<h2><a href="{% url 'main:docs_out' %}">Расходные накладные</a></h2>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>

main/templates/docs_in.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
<h1>Приходные накладные</h1>

<form>
    <label for="doc_number">Номер накладной: </label>
    <input id="doc_number" type="text" name="doc_number">
    <input type="submit" value="OK">
</form>
<br>

<form action="{% url 'main:docs_in_create' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Добавить новую">
</form>
<br>


<table style="width:100%">
  <tr>
    <th>Номер</th>
    <th>Дата</th>
    <th>Описание</th>
    <th></th>
  </tr>
    {% for document in documents %}
        <tr>
            <td>{{document.doc_number}}</td>
            <td>{{document.date_created}}</td>
            <td>{{document.description}}</td>
            <td>
                <a href="{% url 'main:docs_in_print' document.pk %}" target="_blank">Распечатать</a>
                <a href="{% url 'main:docs_in_edit' document.pk %}">Редактировать</a>
            </td>
        </tr>
{% endfor %}
</table>

<h3><a href="{% url 'main:docs' %}">Назад</a></h3>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>
</body>

main/templates/docs_in_edit.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
<h1>Приходная накладная (редактирование)</h1>

<form action="{% url 'main:docs_in_edit' document.pk %}" method="post">
    {% csrf_token %}
    <table>
        {{ form_doc.as_table }}
    </table>
    <input type="submit" value="Записать">
</form>
<br>
<h3>Добавить товары:</h3>
<form action="{% url 'main:docs_in_add_item' document.pk %}" method="post">
    {% csrf_token %}
    <table>
        {{ form_item.as_table }}
    </table>
    <input type="submit" value="Добавить">
</form>
<br>

<table style="width:100%">
  <tr>
    <th>Наименование</th>
    <th>Заводской номер</th>
    <th>Номер паспорта</th>
    <th>Вес</th>
    <th></th>
  </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.factory_number }}</td>
        <td>{{ item.passport_number }}</td>
        <td>{{ item.weight }}</td>
        <td><a href="{% url 'main:docs_in_del_item' item.pk %}">Удалить</a></td>
    </tr>
    {% endfor %}
</table>
<h3><a href="{% url 'main:docs_in' %}">Назад</a></h3>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>
</body>

main/templates/docs_in_print.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>

<p>Организация ООО "Склад"</p>
<p>ИНН 1234567890123</p>
<br>
<br>
<br>
<br>
<br>
<div align="center">
    <h2>Приходная накладная № {{ doc_number }}</h2>
    <h3>от {{ date_created }}</h3>
</div>
<br>

<table style="width:100%">
  <tr>
    <th>Наименование </th>
  </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.name }}</td>
    </tr>
    {% endfor %}
</table>
<br>
<br>
<br>
<br>
<br>
<div align="right">
    <p>Принял___________________________________________</p>
    <br>
    <p>Сдал_____________________________________________</p>
</div>



</body>

main/templates/docs_out.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
<h1>Расходные накладные</h1>

<form>
    <label for="doc_number">Номер накладной: </label>
    <input id="doc_number" type="text" name="doc_number">
    <input type="submit" value="OK">
</form>
<br>

<form action="{% url 'main:docs_out_create' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Добавить новую">
</form>
<br>


<table style="width:100%">
  <tr>
    <th>Номер</th>
    <th>Дата</th>
    <th>Описание</th>
    <th></th>
  </tr>
    {% for document in documents %}
        <tr>
            <td>{{document.doc_number}}</td>
            <td>{{document.date_created}}</td>
            <td>{{document.description}}</td>
            <td>
                <a href="{% url 'main:docs_out_print' document.pk %}" target="_blank">Распечатать</a>
                <a href="{% url 'main:docs_out_edit' document.pk %}">Редактировать</a>
            </td>
        </tr>
{% endfor %}
</table>

<h3><a href="{% url 'main:docs' %}">Назад</a></h3>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>
</body>

main/templates/docs_out_edit.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
<h1>Расходная накладная (редактирование)</h1>

<form action="{% url 'main:docs_out_edit' document.pk %}" method="post">
    {% csrf_token %}
    <table>
        {{ form_doc.as_table }}
    </table>
    <input type="submit" value="Записать">
</form>
<br>
<h3>Добавить товары:</h3>
<form action="{% url 'main:docs_out_add_item' document.pk %}" method="post">
{% csrf_token %}
    <label for="id_factory_number">Заводской номер:</label>
    <input type="text" name="factory_number" placeholder="Введите заводской номер" maxlength="60" required id="id_factory_number">
<input type="submit" value="Добавить">
</form>
<br>

<table style="width:100%">
  <tr>
    <th>Наименование</th>
    <th>Заводской номер</th>
    <th>Номер паспорта</th>
    <th>Вес</th>
    <th></th>
  </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.factory_number }}</td>
        <td>{{ item.passport_number }}</td>
        <td>{{ item.weight }}</td>
        <td><a href="{% url 'main:docs_out_del_item' item.pk %}">Удалить</a></td>
    </tr>
    {% endfor %}
</table>
<h3><a href="{% url 'main:docs_out' %}">Назад</a></h3>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>
</body>

main/templates/docs_out_print.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>

<p>Организация ООО "Склад"</p>
<p>ИНН 1234567890123</p>
<br>
<br>
<br>
<br>
<br>
<div align="center">
    <h2>Расходная накладная № {{ doc_number }}</h2>
    <h3>от {{ date_created }}</h3>
</div>
<br>

<table style="width:100%">
  <tr>
    <th>Наименование </th>
  </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.name }}</td>
    </tr>
    {% endfor %}
</table>
<br>
<br>
<br>
<br>
<br>
<div align="right">
    <p>Принял___________________________________________</p>
    <br>
    <p>Сдал_____________________________________________</p>
</div>



</body>

main/templates/index.html
<h1>Главное меню</h1>
<h2><a href="{% url 'main:docs' %}">Документы</a></h2>
<h2><a href="{% url 'main:reports' %}">Отчет по грузам</a></h2>
<br>
<h3><a href="{% url 'main:logout_view' %}">Выйти</a></h3>

main/templates/login.html
<h1>Введите логин и пароль:</h1>
{% if invalid_login %}<p><strong>{{ invalid_login }}</strong></p>{% endif %}
<form action="{% url 'main:login_view' %}" method="POST">
    {% csrf_token %}
    <table>
        <tr>
            <th><label for="id_username">Логин: </label></th>
            <td><input id="id_username" type="text" name="username"></td>
        </tr>
        <tr>
            <th><label for="id_password">Пароль: </label></th>
            <td><input id="id_password" type="password" name="password"></td>
        </tr>
    </table>
    <br>
    <input type="submit" value="Подтвердтить">
</form>

main/templates/reports.html
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
<h1>Отчет по грузам</h1>

<form>
    <label for="id_item_name">Наименование:</label>
    <input type="text" name="item_name" id="id_item_name">
    <label for="id_factory_number">Заводской номер:</label>
    <input type="text" name="factory_number" id="id_factory_number">
    <label for="id_status">Статус хранения:</label>
    <input type="text" name="status" id="id_status">
    <input type="submit" value="Поиск">
</form>
<br>

<p>Всего {{ total }} записей:</p>
<table style="width:100%">
  <tr>
    <th>Наименование</th>
    <th>Заводской номер</th>
    <th>Номер паспорта</th>
    <th>Вес</th>
    <th>Статус</th>
    <th>Дата прибытия</th>
    <th>Номер приходной накладной</th>
    <th>Дата отбытия</th>
    <th>Номер расходной накладной</th>
  </tr>
    {% for r in records %}
    <tr>
        <td>{{ r.name }}</td>
        <td>{{ r.factory_number }}</td>
        <td>{{ r.passport_number }}</td>
        <td>{{ r.weight }}</td>
        <td>{{ r.current_status }}</td>
        <td>{{ r.date_arrival }}</td>
        <td>{{ r.entry_in }}</td>
        <td>{{ r.date_departure }}</td>
        <td>{{ r.entry_out }}</td>
    </tr>
    {% endfor %}
</table>
<h3><a href="{% url 'main:index' %}">В главное меню</a></h3>
</body>